#!/usr/bin/env bash
# error 404 fix
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx stop
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_error.html
sudo sed -i '/listen 80 default_server/a error_page 404; location = {root /usr/share/nginx/html/404_error.html;/n internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
