#!/usr/bin/env bash
# insert a header
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod '0777' /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx stop
sudo chmod '0777' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_error.html
sudo sed -i '/listen 80 default_server/a error_page 404 /404_error.html; location = /404_error.html {\nroot /usr/share/nginx/html/404_error.html;\n internal;}\n' /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";\n" /etc/nginx/sites-available/default
sudo service nginx restart
