#!/usr/bin/env bash
# Fizzbuzz buzz multiple 5 fizz multiple 3
for (( i=1; i<101; ++i))
do    
    if [ $((i % 3)) -eq 0 -a $((i % 5)) -eq 0 ]
    then
    	echo "FizzBuzz"
	continue
    fi	
    if [ $((i % 3)) -eq 0 ]
    then
    	echo "Fizz"
	continue
    fi
    if [ $((i % 5)) -eq 0 ]
    then 
    	echo "Buzz"
	continue
    fi
    if [ $((i % 3)) -ne 0 ]
    then
    	echo "$i"
    fi
done
