#!/usr/bin/env bash
# This script is displaying hour and minutes
counter=0
echo "Minute: $counter"
while [ "$counter" -le 58 ]
do
    counter=$((counter + 1)) 
    echo $counter	
done

counter=1
echo "Hour: $counter"
while [ "$counter" -le 12 ]
do
    echo $counter
    counter=$((counter + 1))     	
done
