#!/usr/bin/env bash
# This script checks if the file exists
FILE=holbertonschool
if [ -f "$FILE" ]
then
    echo "$FILE file exists"
    if [ -s "$FILE" ] 
    then
    	echo "$FILE file is not empty"
    else
	echo "$FILE is empty"
    fi
    echo "$FILE is a regular file"
fi  
if [ -d "$FILE" ]
then
    echo "$FILE file exists"
    if [ -s "$FILE" ] 
    then
    	echo "$FILE file is not empty"
    else
	echo "$FILE is empty"
    fi
fi    
if [ ! -f "$FILE" -a ! -d "$FILE" ]
then
    echo "$FILE file does not exist"
fi
