#!/usr/bin/env bash
# change user to nginx in nginx server and change port to 8080
sudo pkill -f apache2
sudo chmod ugo+rw  /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
